spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        jdbc:
          lob:
            non_contextual_creation : true
  cache:
    cache-names: pessoas
  jmx:
    default-domain: alimentos